image: truyenhv/awir-deployer

stages:
  - build
  - tag
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

before_script:
  - echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > .builder-creds.json
  - sha256sum .builder-creds.json
  - gcloud auth activate-service-account --key-file=.builder-creds.json
  - gcloud config set project $GCP_PROJECT_ID

.build:
  stage: build
  only:
    - ci
    - develop
    - master
    - tags
    - triggers
  script:
    - gcloud builds submit --config=devops/cloudbuild.yaml --substitutions=_CI_PROJECT_NAME=${CI_PROJECT_NAME},_IMAGE_TAG=${CONFIGURATION}-${IMAGE_TAG},_CONFIGURATION=${CONFIGURATION}

build dev:
  extends: .build
  variables:
    CONFIGURATION: develop

build production:
  extends: .build
  variables:
    CONFIGURATION: production

tag:
  stage: tag
  only:
    - tags
  script:
    - gcloud container images add-tag --project vero-2020 gcr.io/vero-2020/protecton-frontend:$IMAGE_TAG gcr.io/vero-2020/protecton-frontend:$CI_COMMIT_TAG --quiet
    - gcloud container images add-tag --project vero-2020 gcr.io/vero-2020/protecton-frontend:$IMAGE_TAG gcr.io/vero-2020/protecton-frontend:latest --quiet

.deploy:
  stage: deploy
  when: manual
  only:
    - ci
    - develop
    - triggers
  script:
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_CLUSTER_ZONE --project $GCP_PROJECT_ID
    - cd devops && bash deploy.sh

deploy to dev:
  extends: .deploy
  variables:
    ENVIRONMENT: "dev"
    HOST: "dev.withvero.com"

deploy to production:
  extends: .deploy
  variables:
    ENVIRONMENT: "prod"
    HOST: "withvero.com"
  only:
    - ci
    - tags
