version: '2'

services:
  node:
    build: .
    command: sh -c "npm install && npm run build -- --output-path=./dist/out --configuration=production && npm run start"
    volumes:
      - .:/app
    ports:
      - "4200:4200"
